services:
  hidropuga-shiny:
    image: rocker/shiny:4.4.1
    container_name: hidropuga-shiny
    restart: unless-stopped
    ports:
      - "3838:3838"
    environment:
      - TZ=America/Mexico_City
    volumes:
      - /root/apps/hidropuga/app:/srv/shiny-server
      - /root/apps/hidropuga/logs:/var/log/shiny-server
    command: >
      bash -lc "R -e \"options(repos='https://cloud.r-project.org');
      pkgs <- c('shiny','dplyr');
      inst <- rownames(installed.packages());
      miss <- setdiff(pkgs, inst);
      if(length(miss)) install.packages(miss)\" && shiny-server"
