services:
  hidropuga-shiny:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hidropuga-shiny
    restart: unless-stopped
    ports:
      - "${APP_PORT}:3838"
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DIR}:/srv/shiny-server
      - ${LOG_DIR}:/var/log/shiny-server
